# Scanner Implemented with re module

import re

print("Enter Filename: ")
file = input()

f = open(file, "r")
print(f.read())

keywords = {
    "reserved": "def",
    "identifier": "magic_func",
    "symbol": "(",
    "symbol": ")",
    "operator": ":",
    "identifier": "rem",
    "operator": "=",
    "identifier": "num",
    "operator": "%",
    "number": "2",
    "reserved": "if",
    "identifier": "rem",
    "operator": "==",
    "number": "0",
    "symbol": ":",
    "reserved": "return",
    "number": "1",
    "operator": "+",
    "number": "4",
    "reserved": "else",
    "symbol": ":",
    "reserved": "return",
    "number": "0.1",
    "reserved": "for",
    "identifier": "sel_a",
    "reserved": "in",
    "identifier": "range",
    "symbol": "(",
    "number": "10",
    "symbol": ")",
    "symbol": ":",
    "identifier": "a",
    "operator": "=",
    "identifier": "magic_func",
    "symbol": "(",
    "identifier": "sel_a",
    "symbol": ")",
    "reserved": "if",
    "identifier": "a",
    "operator": ">=",
    "number": "1",
    "symbol": ":",
    "identifier": "print",
    "symbol": "(",
    "string": "res:",
    "symbol": ",",
    "identifier": "sel_a",
    "symbol": ")",
    "reserved": "else",
    "symbol": ":",
    "identifier": "print",
    "symbol": "(",
    "string": "res:",
    "symbol": ",",
    "identifier": "sel_a",
    "operator": "*",
    "number": "10.5",
    "symbol": ")"
}
